#!/bin/bash
# posix (os_x or linux) terminal profile
PROMPT_COMMAND=__prompt_command
__prompt_command() {
  local NORMAL_COLOR='\[\e[0m\]'
  local RED='\[\e[0;31m\]'
  local YELLOW='\[\e[0;33m\]'
  local GREY='\[\e[0;37m\]'
  local GREEN='\[\e[0;92m\]'
  local USER='\u'
  local BASENAME='\W'
  PS1="\n${RED}${USER}${NORMAL_COLOR}|${YELLOW}${BASENAME}${GREEN}$(__git_ps1)${NORMAL_COLOR} → "
}

export LSCOLORS="dxfxBxDxbxHxHxBxxghxhx"
export CLICOLOR=1
export EDITOR=vim
export HISTTIMEFORMAT="%y/%m/%d %T "

source ~/Development/codex/posix/dot-git-completion
