#!/bin/bash
# posix (os_x or linux) terminal profile
PROMPT_COMMAND=__prompt_command
__prompt_command() {
  local NORMAL_COLOR='\[\e[0m\]'
  local RED='\[\e[0;31m\]'
  local YELLOW='\[\e[0;33m\]'
  local GREY='\[\e[0;37m\]'
  local GREEN='\[\e[0;92m\]'
  local USER='\u'
  local BASENAME='\W'
  PS1="${RED}${USER}${NORMAL_COLOR}|${YELLOW}${BASENAME}${GREEN}$(__git_ps1)${NORMAL_COLOR} → "
}

export LSCOLORS="dxfxBxDxbxHxHxBxxghxhx"
export CLICOLOR=1
export EDITOR=vim
export HISTTIMEFORMAT="%y/%m/%d %T "

# bash_script_dir is how to get the script's directory in bash.
function bash_script_dir {
  printf 'DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"\n'
}

function rnum () {
  head /dev/urandom | tr -dc 0-9 | head -c "$1" ; echo ''
}
function ralpha () {
  head /dev/urandom | tr -dc a-z | head -c "$1" ; echo ''
}
function ran () {
  head /dev/urandom | tr -dc a-z0-9 | head -c "$1" ; echo ''
}
